CREATE DATABASE DB_LIBRE_ERP
GO

USE DB_LIBRE_ERP
GO

SET DATEFORMAT ymd;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
GO;

CREATE TABLE [TIME_ZONE_CONFIG] (
	ID_TIME_ZONE_CONFIG TINYINT IDENTITY(1,1) PRIMARY KEY,
	COUNTRY NVARCHAR(30),
	TIME_ZONE NVARCHAR(40),
	UTC_OFFSET CHAR(6)
);

CREATE TABLE [USER] (
	ID_USER INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(100),
	EMAIL VARCHAR(150),
	[PASSWORD] NVARCHAR(255),
	CURRENCY_CODE CHAR(3) CHECK (LEN(CURRENCY_CODE) = 3),
	LANG_CODE CHAR(2) CHECK (LEN(LANG_CODE) = 2), 
	ID_TIME_ZONE_CONFIG TINYINT,
	FOREIGN KEY (ID_TIME_ZONE_CONFIG) REFERENCES TIME_ZONE_CONFIG (ID_TIME_ZONE_CONFIG)
);

CREATE TABLE [PRODUCT] (
	ID_PRODUCT INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(100),
	STOCK INT CHECK (STOCK > 0),
	PRICE DECIMAL(10,2) CHECK (PRICE >= 0),
	MIN_STOCK SMALLINT CHECK (MIN_STOCK >= 0),
	IS_ACTIVE BIT,
	UPDATED_AT DATETIME2(0),
	ID_USER INT, 
	FOREIGN KEY (ID_USER) REFERENCES [USER] (ID_USER)
);

CREATE TABLE SALE (
	ID_SALE INT IDENTITY(1,1) PRIMARY KEY,
	[DATE] DATETIME2(0),
	ID_USER INT,
	FOREIGN KEY (ID_USER) REFERENCES [USER] (ID_USER)
);

CREATE TABLE SALE_DETAIL (
	ID_SALE_DETAIL INT IDENTITY(1,1) PRIMARY KEY,
	QUANTITY SMALLINT CHECK (QUANTITY > 0),
	UNIT_PRICE DECIMAL(10,2) CHECK (UNIT_PRICE >= 0),
	ID_PRODUCT INT,
	FOREIGN KEY (ID_PRODUCT) REFERENCES [PRODUCT] (ID_PRODUCT)
);

CREATE TABLE [TRANSACTION] (
	ID_TRANSACTION INT IDENTITY(1,1) PRIMARY KEY,
	[TYPE] CHAR(2) CHECK ([TYPE] = 'IN' OR [TYPE] = 'EX'),
	[DATE] DATETIME2(0),
	AMOUNT DECIMAL(10,2) CHECK(AMOUNT >0),
	[DESCRIPTION] NVARCHAR(100),
	ID_USER INT,
	FOREIGN KEY (ID_USER) REFERENCES [USER] (ID_USER)
);
