-- PRODUCT'S STORED PROCEDURES
-- SPXXX : SP_CREATE_PRODUCT

CREATE OR ALTER PROCEDURE SP_CREATE_PRODUCT
	@ID_USER INT,
	@NAME NVARCHAR(100),
	@PRICE DECIMAL(10,2),
	@MIN_STOCK SMALLINT,
	@ID_RETURN INT OUTPUT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		IF(@PRICE < 0 OR @MIN_STOCK < 0)
		BEGIN
			SET @ID_RETURN = -1;
			SET @ERROR_ID = 1;
			SET @ERROR_DESCRIPTION = 'DATOS NO VALIDOS'
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT 1 FROM [USER] WHERE ID_USER = @ID_USER)
		BEGIN
			SET @ID_RETURN = -1;
			SET @ERROR_ID = 2;
			SET @ERROR_DESCRIPTION = 'USUARIO NO VALIDO'
			ROLLBACK TRANSACTION;
			RETURN;
		END

		INSERT INTO [PRODUCT] ([NAME], PRICE, MIN_STOCK, ID_USER, UPDATED_AT, IS_ACTIVE)
			VALUES (@NAME, @PRICE, @MIN_STOCK, @ID_USER, GETUTCDATE(), 1);

        SET @ID_RETURN = SCOPE_IDENTITY();

        COMMIT TRANSACTION;

        SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

	END TRY

	BEGIN CATCH
		ROLLBACK TRANSACTION;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;   
GO

-- SPXXX : SP_UPDATE_PRODUCT

CREATE OR ALTER PROCEDURE SP_UPDATE_PRODUCT
	@ID_USER INT,
	@ID_PRODUCT INT,
	@NAME NVARCHAR(100),
	@PRICE DECIMAL(10,2),
	@MIN_STOCK SMALLINT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		IF(@PRICE < 0 OR @MIN_STOCK < 0 OR @NAME = '')
		BEGIN
			SET @ERROR_ID = 1;
			SET @ERROR_DESCRIPTION = 'DATOS NO VALIDOS'
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS (SELECT 1 FROM [dbo].[PRODUCT] WHERE ID_PRODUCT = @ID_PRODUCT AND ID_USER = @ID_USER)
		BEGIN
			SET @ERROR_ID = 3;
			SET @ERROR_DESCRIPTION = 'PRODUCTO NO VALIDO'
			ROLLBACK TRANSACTION;
			RETURN;
		END

		UPDATE [PRODUCT]
		SET [NAME] = @NAME, PRICE = @PRICE, MIN_STOCK = @MIN_STOCK, UPDATED_AT = GETUTCDATE()
		WHERE ID_PRODUCT = @ID_PRODUCT

        COMMIT TRANSACTION;

        SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

	END TRY

	BEGIN CATCH
		ROLLBACK TRANSACTION;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;
GO

-- SPXXX : SP_GET_ACTIVE_PRODUCTS

CREATE OR ALTER PROCEDURE SP_GET_ACTIVE_PRODUCTS
	@ID_USER INT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		IF NOT EXISTS (SELECT 1 FROM [dbo].[USER] WHERE  ID_USER = @ID_USER)
		BEGIN
			SET @ERROR_ID = 2;
			SET @ERROR_DESCRIPTION = 'USUARIO NO VALIDO'
			RETURN;
		END

		SELECT [ID_PRODUCT], [NAME], [STOCK], [PRICE], [MIN_STOCK]
		FROM [dbo].[PRODUCT]
		WHERE ID_USER = @ID_USER AND IS_ACTIVE = 1

        SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

	END TRY
	BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;
GO

-- SPXXX : SP_DEACTIVE_PRODUCT

CREATE OR ALTER PROCEDURE SP_DEACTIVATE_PRODUCT
	@ID_USER INT,
	@ID_PRODUCT INT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION

		IF NOT EXISTS(SELECT 1 FROM [PRODUCT] WHERE @ID_PRODUCT = ID_PRODUCT AND @ID_USER= ID_USER AND IS_ACTIVE = 1)
		BEGIN
			SET @ERROR_ID = 3;
			SET @ERROR_DESCRIPTION = 'PRODUCT NOT FOUND'
			ROLLBACK TRANSACTION;
			RETURN;
		END

		UPDATE [PRODUCT]
		SET IS_ACTIVE = 0
		WHERE ID_PRODUCT = @ID_PRODUCT AND IS_ACTIVE = 1 AND ID_USER = @ID_USER

		SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;
GO

-- SPXXX : SP_INCREASE_PRODUCT_STOCK

CREATE OR ALTER PROCEDURE SP_INCREASE_PRODUCT_STOCK
	@ID_USER INT,
	@ID_PRODUCT INT,
	@QUANTITY INT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		IF (@QUANTITY < 0)
		BEGIN
			SET @ERROR_ID = 4;
			SET @ERROR_DESCRIPTION = 'WRONG DATA'
			ROLLBACK TRANSACTION;
			RETURN;
		END
		IF NOT EXISTS(SELECT 1 FROM [PRODUCT] WHERE @ID_PRODUCT = ID_PRODUCT AND @ID_USER= ID_USER AND IS_ACTIVE = 1)
		BEGIN
			SET @ERROR_ID = 3;
			SET @ERROR_DESCRIPTION = 'PRODUCT NOT FOUND'
			ROLLBACK TRANSACTION;
			RETURN;
		END

		UPDATE [PRODUCT]
		SET STOCK = (STOCK + @QUANTITY)
		WHERE ID_PRODUCT = @ID_PRODUCT AND IS_ACTIVE = 1 AND ID_USER = @ID_USER

		SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;
GO

-- SPXXX : SP_CREATE_USER

CREATE OR ALTER PROCEDURE SP_CREATE_USER
	@NAME NVARCHAR(100),
	@EMAIL NVARCHAR(150),
	@PASSWORD NVARCHAR(255),
	@CURRENCY_CODE CHAR(3),
	@LANG_CODE CHAR(2),
	@ID_TIME_ZONE TINYINT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		IF EXISTS( SELECT 1 FROM [USER] WHERE EMAIL = @EMAIL)
		BEGIN
			SET @ERROR_ID = 5;
			SET @ERROR_DESCRIPTION = 'EMAIL ALREADY EXISTS';
			ROLLBACK TRANSACTION;
			RETURN;
		END

		IF(LEN(@CURRENCY_CODE) <> 3 OR LEN(@LANG_CODE) <>2)
		BEGIN
			SET @ERROR_ID = 4;
			SET @ERROR_DESCRIPTION = 'WRONG DATA';
			ROLLBACK TRANSACTION;
			RETURN;
		END

		IF NOT EXISTS(SELECT 1 FROM TIME_ZONE_CONFIG WHERE ID_TIME_ZONE_CONFIG = @ID_TIME_ZONE)
		BEGIN
			SET @ERROR_ID = 6;
			SET @ERROR_DESCRIPTION = 'TIME ZONE NOT FOUND';
			ROLLBACK TRANSACTION;
			RETURN;
		END

		INSERT INTO [USER] ([NAME], [EMAIL], [PASSWORD], CURRENCY_CODE, LANG_CODE, ID_TIME_ZONE_CONFIG)
			VALUES (@NAME, @EMAIL, @PASSWORD, @CURRENCY_CODE, @LANG_CODE, @ID_TIME_ZONE);

		SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH

END;
GO

-- SPXXX : SP_LOGIN_USER

CREATE OR ALTER PROCEDURE SP_LOGIN_USER
	@EMAIL VARCHAR(150),
	@PASSWORD NVARCHAR(255),
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		IF NOT EXISTS(SELECT 1 FROM [USER] WHERE EMAIL = @EMAIL AND [PASSWORD] = @PASSWORD)
		BEGIN 
		-- ERROR
			SET @ERROR_ID = 7;
			SET @ERROR_DESCRIPTION = 'INVALID CREDENTIALS';
			RETURN;
		END

		SELECT ID_USER,
			[NAME],
			LANG_CODE,
			CURRENCY_CODE,
			TZC.UTC_OFFSET
		FROM [USER] U
		INNER JOIN TIME_ZONE_CONFIG TZC ON TZC.ID_TIME_ZONE_CONFIG = U.ID_TIME_ZONE_CONFIG
		WHERE U.EMAIL = @EMAIL AND U.[PASSWORD] = @PASSWORD

		SET @ERROR_ID = NULL;
		SET @ERROR_DESCRIPTION = NULL;
	END TRY
	BEGIN CATCH
		SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;
GO

-- SPXXX : SP_UPDATE_USER_PROFILE

CREATE OR ALTER PROCEDURE SP_UPDATE_USER
	@ID_USER INT,
	@NAME NVARCHAR(100),
	@CURRENCY_CODE CHAR(3),
	@LANG_CODE CHAR(2),
	@ID_TIME_ZONE TINYINT,
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION NVARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		IF NOT EXISTS(SELECT 1 FROM [USER] WHERE ID_USER = @ID_USER)
		BEGIN
				SET @ERROR_ID = 2;
				SET @ERROR_DESCRIPTION = 'USUARIO NO VALIDO'
				ROLLBACK TRANSACTION;
				RETURN;
		END

		IF (LEN(@CURRENCY_CODE) <> 3) OR (LEN(@LANG_CODE) <> 2)
		BEGIN
				SET @ERROR_ID = 4;
				SET @ERROR_DESCRIPTION = 'WRONG DATA'
				ROLLBACK TRANSACTION;
				RETURN;
		END

		IF NOT EXISTS (SELECT 1 FROM TIME_ZONE_CONFIG WHERE ID_TIME_ZONE_CONFIG = @ID_TIME_ZONE)
		BEGIN
				SET @ERROR_ID = 4;
				SET @ERROR_DESCRIPTION = 'WRONG DATA'
				ROLLBACK TRANSACTION;
				RETURN;
		END

		UPDATE [USER]
		SET [NAME] = @NAME, CURRENCY_CODE = @CURRENCY_CODE, LANG_CODE = @LANG_CODE, ID_TIME_ZONE_CONFIG = @ID_TIME_ZONE
		WHERE ID_USER = @ID_USER


		SET @ERROR_ID = NULL;
        SET @ERROR_DESCRIPTION = NULL;

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPTION = 'ERROR SQL';
	END CATCH
END;

-- SPXXX : SP_GET_TIME_ZONES

CREATE OR ALTER PROCEDURE SP_GET_TIME_ZONES
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION NVARCHAR(MAX) OUTPUT
AS 
BEGIN
	BEGIN TRY
	
		SELECT 
			ID_TIME_ZONE_CONFIG,
			COUNTRY,
			TIME_ZONE
		FROM
			TIME_ZONE_CONFIG;

		SET @ERROR_ID = NULL;
		SET ERROR_DESCRIPTION = NULL;
	END TRY
	BEGIN CATCH
		SET @ERROR_ID = ERROR_NUMBER();
		SET ERROR_DESCRIPTION = 'ERROR_SQL';
	END CATCH
END;

-- SPXXX : SP_CREATE_TRANSACTION

CREATE OR ALTER PROCEDURE SP_CREATE_TRANSACTION
	@ID_USER INT,
    @TYPE CHAR(2),
    @AMOUNT DECIMAL(10, 2),
    @DESCRIPTION NVARCHAR(100),
	@ERROR_ID INT OUTPUT,
	@ERROR_DESCRIPTION NVARCHAR(MAX) OUTPUT
AS 
BEGIN

	BEGIN TRY
		BEGIN TRANSACTION


			IF NOT EXISTS(SELECT 1 FROM [USER] WHERE ID_USER = @ID_USER)
			BEGIN
				SET @ERROR_ID = 2;
				SET ERROR_DESCRIPTION = 'USER_NOT_FOUND';
				ROLLBACK TRANSACTION;
				RETURN;
			END

			IF @TYPE NOT IN ('In','Ex')
			BEGIN 
				SET @ERROR_ID = 3;
				SET ERROR_DESCRIPTION = 'INVALID_TYPE';
				ROLLBACK TRANSACTION;
				RETURN;
			END

			IF @AMOUNT <= 0
			BEGIN
					SET @ERROR_ID = 4;
					SET ERROR_DESCRIPTION = 'INVALID_AMOUNT';
					ROLLBACK TRANSACTION;
					RETURN;
			END

		INSERT INTO [TRANSACTION] (TYPE, DATE, AMOUNT, DESCRIPTION, ID_USER) 
		VALUES (@TYPE, GETUTCDATE(), @AMOUNT, @DESCRIPTION, @ID_USER)

		COMMIT TRANSACTION;
		SET @ERROR_ID = NULL;
		SET ERROR_DESCRIPTION = NULL;

	END TRY
	BEGIN CATCH
	ROLLBACK TRANSACTION;
		SET @ERROR_ID = ERROR_NUMBER();
		SET ERROR_DESCRIPTION = 'ERROR_SQL';
	END CATCH
END;

CREATE TYPE SALE_DETAIL_TYPE AS TABLE
(
    ID_PRODUCT INT,
    QUANTITY INT
);